### ISSUE TITLE
Fix logos in dark mode

### ISSUE THREAD

**Issue by Rahma-AlWadhahi** [Aryamanz29/Aryamanz29#3]
### Description
Cool profile!. I have noticed that some of the logos are not compatible with dark mode shown below in Screenshots.

### Screenshot
<img width="876" alt="Screen Shot 2021-05-03 at 22 05 57" src="https://user-images.githubusercontent.com/61970868/116914408-c01c1780-ac5b-11eb-887e-f6c756db5a07.png">

**Comment by Aryamanz29** [comment]
> ### Description
> Cool profile!. I have noticed that some of the logos are not compatible with dark mode shown below in Screenshots.
> 
> ### Screenshot
> <img alt="Screen Shot 2021-05-03 at 22 05 57" width="876" src="https://user-images.githubusercontent.com/61970868/116914408-c01c1780-ac5b-11eb-887e-f6c756db5a07.png">

@Rahma-AlWadhahi  Thanks for suggesting! Profile updated 🤗
